import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import AsideBar from "@/components/asidebar";
import { PathCrumb } from "@/components/pathCrumb";
import { Button } from "@/components/ui/button";
import { Divide, Mail } from "lucide-react";
import { Toaster } from "@/components/ui/toaster";
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
        <AsideBar >{children}</AsideBar>
        <section className="lg:ml-12 md:ml-12">
      <Navbar />
          <main className="bg-[#e7e3ff] min-h-screen">

            <span className="text-[#ff790e] text-[#34a853] md:text-[#1bdb8a] sm:text-[#a5aa85]" />
            <div className="px-20 py-10">
              <div className="flex justify-between items-center">
                <div>
                  <PathCrumb />
                  <h4 className="text-2xl mt-2 font-semibold">
                    <span className="text-[#ff790e] font-bold">MKA-BD<span /></span> Blood Donours.
                  </h4>
                </div>
                <div className="space-x-3">
                  <Button className="border border-[#ff790e] text-[0.795rem]" variant="ghost">
                    <Mail className="mr-2 h-3.5 w-3.5" /> Login with Email
                  </Button>
                </div>
              </div>
              <Separator className=" my-4 bg-slate-300" />
              {children}
            </div>
          </main>
        </section>
      </body>
    </html>
  );
}
