import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import AsideBar from "@/components/asidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AsideBar >{children}</AsideBar>
        <section className="lg:ml-10 md:ml-10">{children}
        </section>
      </body>
    </html>
  );
}
